# Sử dụng Python 3.9 hoặc 3.10 bản slim (nhẹ, tối ưu cho container)
FROM python:3.9-slim

# Thiết lập thư mục làm việc mặc định trong container
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY quality_control/requirements.txt .

# Cài đặt các thư viện
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pandera
# Copy toàn bộ source code vào container
COPY ../data /app/data
COPY ../log /app/log 
COPY . .
